### ISSUE TITLE
to many open files

### ISSUE THREAD

**Issue by abma** [spring/relayhost#1]
ERROR - 2015-11-21 17:31:38,504 - [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/relayhost/bots/tasbot_framework/relayhost/tasbot/client.py", line 61, in connect
    self.socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
  File "/usr/lib/python2.7/socket.py", line 187, in **init**
    _sock = _realsocket(family, type, proto)
error: [Errno 24] Too many open files

**Comment by abma** [comment]
seems the autohost socket to spring isn't closed

**Comment by abma** [comment]
very likely autohost.py needs some function to close the socket to spring when spring exited

**Comment by abma** [comment]
ython  27944 relayhost  197r  FIFO       0,8      0t0 169644449 pipe
python  27944 relayhost  198u  IPv4 169683179      0t0       UDP localhost:9011 
python  27944 relayhost  199u  IPv4 169889583      0t0       UDP localhost:9010 
python  27944 relayhost  200u  IPv4 170432301      0t0       UDP localhost:9010 
python  27944 relayhost  201u  IPv4 169909311      0t0       UDP localhost:9011 
python  27944 relayhost  202u  IPv4 169909750      0t0       UDP localhost:9011 
python  27944 relayhost  203u  IPv4 170651878      0t0       UDP localhost:9010 
python  27944 relayhost  204u  IPv4 169909789      0t0       UDP localhost:9011 
python  27944 relayhost  205u  IPv4 169910187      0t0       UDP localhost:9011 
python  27944 relayhost  206u  IPv4 169932191      0t0       UDP localhost:9011 
python  27944 relayhost  207u  IPv4 169936275      0t0       UDP localhost:9011 
python  27944 relayhost  208u  IPv4 169932596      0t0       UDP localhost:9011 
...

**Comment by abma** [comment]
https://github.com/spring/relayhost/commit/5a64cd9400e4e56466cd11d4b5b98ae4e27cca35
